cache:
    untracked: true

stages:
    - test

test:
    stage: test
    script:
      - php -v
      - rm -rf vendor
      - composer install -o
      - ./vendor/bin/phpunit --coverage-text --colors=never